# Generated by Django 4.0.5 on 2022-07-14 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_sessionyearmodel_session_end_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='status',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='session_year_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.sessionyearmodel'),
        ),
    ]
