# Generated by Django 4.0.5 on 2022-07-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_adminhod_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(default='media/avatar.svg', upload_to='media/profile_pic'),
        ),
    ]
