# Generated by Django 4.0.5 on 2022-07-15 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_adminhod_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminhod',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', upload_to='profiles'),
        ),
        migrations.AlterField(
            model_name='students',
            name='profile_pic',
            field=models.ImageField(default='avatar.svg', upload_to='profile_pic'),
        ),
    ]
