# Generated by Django 4.0.5 on 2022-07-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_adminhod_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminhod',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='students',
            name='profile_pic',
        ),
    ]
